# Taps
tap "homebrew/bundle"
tap "homebrew/services"

# Binaries
brew "mas" # Mac App Store manager

# Apps
cask "boop"
cask "bruno"
cask "dash"
cask "docker"
cask "firefox"
cask "fleet"
cask "intellij-idea-ce"
cask "maccy"
cask "obsidian"
brew "ollama", restart_service: true
cask "ollamac"
cask "rectangle"
cask "warp"

#oh-my-zsh
brew "zsh-autocomplete"
brew "zsh-autosuggestions"

# Mac App Store
mas "1Password for Safari", id: 1569813296
mas "Grocy Mobile", id: 1567803209
mas "Snippet", id: 1613020051
mas "Tailscale", id: 1475387142
